name: Frontend UI Tests

on: push

jobs:
    test:
        name: Test & Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Ensure Node
              uses: actions/setup-node@master
              with:
                  node-version: 12.x

            - name: Install
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run test

    build_storybook:
        name: Storybook
        runs-on: ubuntu-latest
        needs:
            - test
        steps:
            - uses: actions/checkout@v1
            - name: Ensure Node
              uses: actions/setup-node@master
              with:
                  node-version: 12.x

            - name: Install
              run: npm ci

            - name: Build Storybook
              run: npm run build-storybook

    build:
        name: Build & Publish
        runs-on: ubuntu-latest
        needs:
            - test
        if: github.event_name == 'push'
        steps:
            - uses: actions/checkout@v1

            - name: Docker Login
              run: |
                  echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            - name: Build
              uses: roleypoly/actions/dxt@master
              if: github.event_name == 'push'
              with:
                  tag: ${{ github.repository }}:${{ github.sha }}
                  platforms: linux/amd64
                  qemu: 'false'
                  push: 'true'

            - name: Retag Image
              if: github.event_name == 'push'
              run: |
                  retag() {
                  curl -sSL https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64 > $HOME/buildx &&\
                  chmod a+x $HOME/buildx &&\
                  $HOME/buildx imagetools create --tag "${{ github.repository }}:$1" "${{ github.repository }}:${{ github.sha }}" && \
                  exit 0
                  }
                  test ${{ github.ref }} = "refs/heads/master" && retag latest || \
                  test ${{ github.ref }} = "refs/heads/develop" && retag next || \
                  test ${{ github.ref }} = "refs/heads/ci-testing" && retag scratch || \
                  echo "not a well-known branch, not retagging"

    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs:
            - build
        if: github.event_name == 'push'
        steps:
            - name: Deploy to Staging
              uses: roleypoly/actions/deploy@master
              if: github.ref == 'refs/heads/develop'
              with:
                  environment: staging
                  new_tag: ${{ github.sha }}
                  app: ui
                  github_auth_token: ${{ secrets.GITOPS_TOKEN }}

            - name: Deploy to Production
              uses: roleypoly/actions/deploy@master
              if: github.ref == 'refs/heads/master'
              with:
                  environment: production
                  new_tag: ${{ github.sha }}
                  app: ui
                  github_auth_token: ${{ secrets.GITOPS_TOKEN }}
