name: Frontend UI Tests

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Ensure Node
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

  build_storybook:
    name: Storybook
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v1
      - name: Ensure Node
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v1
      - name: Ensure Node
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
# missing: final output build. docker? at least this is still useful as it is.
